version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bundler
    versions:
    - 2.2.10
    - 2.2.11
    - 2.2.12
    - 2.2.13
    - 2.2.14
    - 2.2.7
    - 2.2.8
    - 2.2.9
  - dependency-name: pry
    versions:
    - 0.13.1
